import { Project, Task, AssessmentMetric } from './types';

export const initialProjects: Project[] = [
  {
    id: 'p-hotel-1',
    name: 'The Grand Horizon Hotel',
    type: 'hotel',
    description: 'Five-star luxury hotel reopening after comprehensive modernization.',
    manager: 'Eleanor Vance',
    targetDate: '2026-11-01',
  },
  {
    id: 'p-office-1',
    name: 'Apex Tower Renovation',
    type: 'office',
    description: 'Premium Grade-A office tower lobby and facilities upgrade.',
    manager: 'Marcus Thorne',
    targetDate: '2026-08-15',
  }
];

export const initialTasks: Task[] = [
  // Hotel Tasks
  {
    id: 't-h-1',
    projectId: 'p-hotel-1',
    title: 'Structural Integrity Assessment',
    description: 'Complete engineering review of the main lobby and ballroom structures.',
    status: 'completed',
    priority: 'critical',
    phase: 'assessment',
    dueDate: '2026-04-10',
    assignee: 'Engineering Dept',
    isChecklistItem: true,
  },
  {
    id: 't-h-2',
    projectId: 'p-hotel-1',
    title: 'HVAC System Overhaul',
    description: 'Replace legacy air conditioning units with high-efficiency smart systems.',
    status: 'in-progress',
    priority: 'high',
    phase: 'renovation',
    dueDate: '2026-06-15',
    assignee: 'ClimateTech Inc.',
  },
  {
    id: 't-h-3',
    projectId: 'p-hotel-1',
    title: 'Executive Chef Recruitment',
    description: 'Finalize interviews and tasting sessions for the signature restaurant.',
    status: 'in-progress',
    priority: 'high',
    phase: 'staffing',
    dueDate: '2026-05-20',
    assignee: 'HR Department',
  },
  {
    id: 't-h-4',
    projectId: 'p-hotel-1',
    title: 'Procure Frette Linens',
    description: 'Order 1000 sets of premium 800-thread-count linens for all suites.',
    status: 'pending',
    priority: 'medium',
    phase: 'procurement',
    dueDate: '2026-07-01',
    assignee: 'Procurement Team',
  },
  {
    id: 't-h-5',
    projectId: 'p-hotel-1',
    title: 'Final Health & Safety Inspection',
    description: 'City municipal inspection for kitchen and pool areas.',
    status: 'pending',
    priority: 'critical',
    phase: 'handover',
    dueDate: '2026-10-15',
    assignee: 'Compliance Officer',
    isChecklistItem: true,
  },

  // Office Tasks
  {
    id: 't-o-1',
    projectId: 'p-office-1',
    title: 'Elevator Modernization Audit',
    description: 'Assess current elevator speeds and control systems.',
    status: 'completed',
    priority: 'high',
    phase: 'assessment',
    dueDate: '2026-03-20',
    assignee: 'Vertical Systems LLC',
    isChecklistItem: true,
  },
  {
    id: 't-o-2',
    projectId: 'p-office-1',
    title: 'Lobby Marble Restoration',
    description: 'Polish and seal the Italian marble flooring in the main atrium.',
    status: 'in-progress',
    priority: 'medium',
    phase: 'renovation',
    dueDate: '2026-05-10',
    assignee: 'StoneCraft',
  },
  {
    id: 't-o-3',
    projectId: 'p-office-1',
    title: 'Fiber Optic Backbone Upgrade',
    description: 'Install CAT8 and dual-redundant fiber lines for all tenant floors.',
    status: 'review',
    priority: 'critical',
    phase: 'renovation',
    dueDate: '2026-04-30',
    assignee: 'IT Infrastructure',
  },
  {
    id: 't-o-4',
    projectId: 'p-office-1',
    title: 'Smart Access Control Installation',
    description: 'Deploy biometric and mobile-NFC turnstiles in the lobby.',
    status: 'pending',
    priority: 'high',
    phase: 'procurement',
    dueDate: '2026-06-01',
    assignee: 'Security Dept',
  },
  {
    id: 't-o-5',
    projectId: 'p-office-1',
    title: 'Tenant Handover Documentation',
    description: 'Prepare welcome kits and facility manuals for returning tenants.',
    status: 'pending',
    priority: 'low',
    phase: 'handover',
    dueDate: '2026-07-20',
    assignee: 'Property Management',
    isChecklistItem: true,
  }
];

export const seedMetricsData = [
  { category: 'Water & Plumbing', item: 'Storage water tanks', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Calorifiers', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Sump pit lifting stations', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Sanitary system', vendor: 'VP Pine Co.,Ltd' },
  { category: 'Water & Plumbing', item: 'Domestic water pumps', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Hot water / Heat Pump', vendor: 'VP Pine Co.,Ltd' },
  { category: 'Water & Plumbing', item: 'Waste water Treatment system', vendor: 'ATP Solutions & Innovations Co., Ltd.' },
  { category: 'Water & Plumbing', item: 'CHP, CDP PUMP', vendor: 'Aemstronge' },
  { category: 'HVAC & Cooling', item: 'Air intakes (Check if bagged off)', vendor: 'Internal' },
  { category: 'HVAC & Cooling', item: 'Air Chiller Tane 365 Ton', vendor: 'Mr. Narat' },
  { category: 'HVAC & Cooling', item: 'Cooling Tower', vendor: 'TRUWATER THAILAND CO., LTD.' },
  { category: 'HVAC & Cooling', item: 'Air Con System', vendor: 'VP Pine Co.,Ltd' },
  { category: 'HVAC & Cooling', item: 'AHU\'s & FCU\'s (Check filters)', vendor: 'Internal / HVAC Vendor' },
  { category: 'HVAC & Cooling', item: 'Toilet extract & Smoke fans', vendor: 'Internal' },
  { category: 'HVAC & Cooling', item: 'Staircase Pressurisation Fans', vendor: 'Internal' },
  { category: 'HVAC & Cooling', item: 'Plant room ventilation', vendor: 'Internal' },
  { category: 'Electrical & Safety', item: 'MDB System', vendor: 'Mr. Chusak' },
  { category: 'Electrical & Safety', item: 'Generator Machine', vendor: 'Effective Strength EngineeringCo.,Ltd' },
  { category: 'Electrical & Safety', item: 'Car park & plantroom power/lighting', vendor: 'Internal' },
  { category: 'Electrical & Safety', item: 'Fire Alarm System', vendor: 'Mr.Decha' },
  { category: 'Electrical & Safety', item: 'Fire Lift Safety System', vendor: 'Gewarzoe Co., Ltd' },
  { category: 'Electrical & Safety', item: 'CCTV System', vendor: 'Mr.Wasu Yakham' },
  { category: 'Electrical & Safety', item: 'ANSUL System', vendor: 'Magpie Blaztech Co.,Ltd' },
  { category: 'Electrical & Safety', item: 'BMS (Clocks and equipment status)', vendor: 'Internal' },
  { category: 'Kitchen & F&B', item: 'All Kitchen equipment', vendor: 'SUNMEN Corporation' },
  { category: 'Kitchen & F&B', item: 'Gas System', vendor: 'CENTRAL LPG Piping Development Co., Ltd.' },
  { category: 'Kitchen & F&B', item: 'Walk in Chiller Cool Room', vendor: 'B-Cool air Conditioning Co.,Ltd' },
  { category: 'Kitchen & F&B', item: 'Freezers & Upright freezers', vendor: 'Internal / Refrigeration Vendor' },
  { category: 'Kitchen & F&B', item: 'Ice machines', vendor: 'Internal' },
  { category: 'IT & Technology', item: 'IT Network System', vendor: 'Mr.Wasu Yakham' },
  { category: 'IT & Technology', item: 'RCU (Guest Room)', vendor: 'INTRONICS CO.,LTD' },
  { category: 'IT & Technology', item: 'Door VinCard (Guest Room)', vendor: 'FORTRESS LAND Company Limited' },
  { category: 'IT & Technology', item: 'Interactive TV & Background music', vendor: 'Internal / IT' },
  { category: 'IT & Technology', item: 'Wireless connectivity', vendor: 'Internal / IT' },
  { category: 'IT & Technology', item: 'AV System', vendor: 'D.V.I Solution' },
  { category: 'Leisure & General', item: 'Swimming Pool & Filters', vendor: 'POOL&SPA Myanmar CO.,LTD' },
  { category: 'Leisure & General', item: 'Laundry Machine', vendor: 'RENZACCI SPA' },
  { category: 'Leisure & General', item: 'Lift Machine / Elevators', vendor: 'Myanmar Jardine Schindler Ltd' },
  { category: 'Leisure & General', item: 'Gym & Spa equipment', vendor: 'Internal' },
  { category: 'Leisure & General', item: 'Landscape irrigation & lighting', vendor: 'Internal' },
  { category: 'Leisure & General', item: 'Guestrooms & public spaces (Furniture)', vendor: 'Internal / Housekeeping' },
  { category: 'Leisure & General', item: 'Building signage & BMU', vendor: 'Internal' }
];

export const initialMetrics: AssessmentMetric[] = [
  { id: 'm1', projectId: 'p-hotel-1', category: 'Structural', item: 'Foundation Integrity', status: 'pass', notes: 'Inspected by structural engineer. No issues.' },
  { id: 'm2', projectId: 'p-hotel-1', category: 'Systems', item: 'Plumbing Mains', status: 'fail', notes: 'Corrosion detected in East Wing mains. Requires replacement.' },
  { id: 'm3', projectId: 'p-hotel-1', category: 'Safety', item: 'Fire Suppression System', status: 'pending', notes: 'Awaiting municipal pressure test.' },
  { id: 'm4', projectId: 'p-office-1', category: 'Systems', item: 'HVAC Chillers', status: 'pass', notes: 'Operating at 94% efficiency.' },
  { id: 'm5', projectId: 'p-office-1', category: 'Aesthetics', item: 'Facade Glass Integrity', status: 'pass', notes: 'Drone inspection complete.' },
];

export const seedTasksData = [
  { originalId: 'T01', phase: 'assessment', title: 'Take all utility readings.', priority: 'high', assignee: 'Internal Team', dependencies: [] },
  { originalId: 'T02', phase: 'renovation', title: 'Turn on all Car park and plantroom power and lighting.', priority: 'high', assignee: 'Internal Team', dependencies: [] },
  { originalId: 'T03', phase: 'renovation', title: 'Re-start all sump pit lifting stations.', priority: 'high', assignee: 'Internal Team', dependencies: ['T02'] },
  { originalId: 'T04', phase: 'procurement', title: "Re-instate critical AMC's (Elevators, Fire Alarm, CCTV, etc.).", priority: 'high', assignee: 'Jardine Schindler / Mr. Decha / Mr. Wasu', dependencies: [] },
  { originalId: 'T05', phase: 'assessment', title: 'Re-set all BMS clocks and restart BMS to check equipment status.', priority: 'high', assignee: 'Internal Team', dependencies: ['T02'] },
  { originalId: 'T06', phase: 'staffing', title: 'Power up administration work areas.', priority: 'high', assignee: 'Internal Team', dependencies: ['T02'] },
  { originalId: 'T07', phase: 'assessment', title: 'Check Water tank levels.', priority: 'high', assignee: 'Internal Team', dependencies: [] },
  { originalId: 'T08', phase: 'assessment', title: 'Take samples of water (Storage tanks, Calorifiers, Showers, Kitchens, Pools) and send to lab.', priority: 'high', assignee: 'Internal Team / External Lab', dependencies: ['T07'] },
  { originalId: 'T09', phase: 'planning', title: 'Receive Water Quality Lab Results.', priority: 'high', assignee: 'External Lab', dependencies: ['T08'] },
  { originalId: 'T10', phase: 'procurement', title: 'Chemically treat all Storage tanks.', priority: 'high', assignee: 'Internal / Water Treatment Vendor', dependencies: ['T09 (Only if samples fail)'] },
  { originalId: 'T11', phase: 'renovation', title: 'Start water refilling procedure.', priority: 'high', assignee: 'Internal Team', dependencies: ['T09 (Requires clear results)'] },
  { originalId: 'T12', phase: 'renovation', title: 'Send team to uppermost guest rooms to open floor risers/bathroom fittings for air release.', priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T11'] },
  { originalId: 'T13', phase: 'renovation', title: 'Start domestic water pump and Hot water.', priority: 'high', assignee: 'VP Pine Co.,Ltd', dependencies: ['T11'] },
  { originalId: 'T14', phase: 'renovation', title: 'Remove all air from all systems.', priority: 'high', assignee: 'Maintenance Team', dependencies: ['T12', 'T13'] },
  { originalId: 'T15', phase: 'renovation', title: 'Re-start water treatment/ softeners/ filtration systems.', priority: 'medium', assignee: 'ATP Solutions', dependencies: ['T13'] },
  { originalId: 'T16', phase: 'handover', title: 'Uncover all furniture.', priority: 'high', assignee: 'Internal Team', dependencies: [] },
  { originalId: 'T17', phase: 'renovation', title: 'Spring clean all guestrooms and public spaces (launder, dry clean, carpet).', priority: 'medium', assignee: 'Housekeeping', dependencies: ['T16'] },
  { originalId: 'T18', phase: 'renovation', title: 'Carry out professional cleaning to all areas (if used as Quarantine unit).', priority: 'high', assignee: 'Professional Cleaners', dependencies: [] },
  { originalId: 'T19', phase: 'renovation', title: 'Fully service equipment in Authority-used areas wearing full disposable PPE.', priority: 'high', assignee: 'Maintenance Team', dependencies: ['T18'] },
  { originalId: 'T20', phase: 'procurement', title: "Replace all Filters to AHU's, FCU's (treat replaced material as hazardous).", priority: 'high', assignee: 'Maintenance Team', dependencies: [] },
  { originalId: 'T21', phase: 'assessment', title: 'Remove bagging from all air intakes prior to restarting units.', priority: 'high', assignee: 'Internal Team', dependencies: [] },
  { originalId: 'T22', phase: 'renovation', title: "Re-start AHU's and restart/re-vent all FCU's.", priority: 'high', assignee: 'Internal / HVAC Vendor', dependencies: ['T20', 'T21'] },
  { originalId: 'T23', phase: 'renovation', title: 'Re-start all Chillers, circulating pumps, and drain/restart cooling towers.', priority: 'high', assignee: 'Mr. Narat / TRUWATER', dependencies: ['T02'] },
  { originalId: 'T24', phase: 'handover', title: 'Start-up cooling to guest rooms and set to 23C.', priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T23'] },
  { originalId: 'T25', phase: 'renovation', title: 'Vent all Chilled Water/ Heating.', priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T24'] },
  { originalId: 'T26', phase: 'renovation', title: 'Power up Toilet extract, Smoke fans, and Staircase Pressurisation Fans.', priority: 'high', assignee: 'Maintenance Team', dependencies: ['T02'] },
  { originalId: 'T27', phase: 'renovation', title: 'Re-start/turn off all plant room ventilation.', priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T02'] },
  { originalId: 'T28', phase: 'renovation', title: 'Carry out venting procedures to locker rooms, kitchens, laundries, and public areas.', priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T26', 'T27'] },
  { originalId: 'T29', phase: 'staffing', title: 'Re-open loading dock and all Kitchens.', priority: 'medium', assignee: 'Internal Team', dependencies: [] },
  { originalId: 'T30', phase: 'renovation', title: 'Carry out Major Steward clean of all kitchens and Refrigeration Equipment.', priority: 'medium', assignee: 'Steward Team', dependencies: ['T29'] },
  { originalId: 'T31', phase: 'renovation', title: 'Re-start all Cold rooms, Freezers, Upright freezers and cold rooms.', priority: 'medium', assignee: 'B-Cool / Internal', dependencies: ['T30'] },
  { originalId: 'T32', phase: 'renovation', title: 'Power up Kitchens and all refrigeration units.', priority: 'medium', assignee: 'SUNMEN Corporation', dependencies: ['T30'] },
  { originalId: 'T33', phase: 'renovation', title: "Re-start Kitchen extract and Outlet Kitchen AHS's.", priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T32'] },
  { originalId: 'T34', phase: 'handover', title: 'Start filling ice machines on floors.', priority: 'high', assignee: 'F&B / Maintenance', dependencies: ['T09 (Requires clear results)'] },
  { originalId: 'T35', phase: 'handover', title: 'Start making ice.', priority: 'high', assignee: 'F&B Team', dependencies: ['T09', 'T34'] },
  { originalId: 'T36', phase: 'staffing', title: 'Commence cooking operations.', priority: 'high', assignee: 'Culinary Team', dependencies: ['T09', 'T32 (Requires clear results)'] },
  { originalId: 'T37', phase: 'handover', title: 'Re-instate guest floors services (power, water, cooling).', priority: 'high', assignee: 'Maintenance Team', dependencies: ['T02', 'T13', 'T24'] },
  { originalId: 'T38', phase: 'renovation', title: 'Start Calorifiers, heat pumps, and boilers.', priority: 'medium', assignee: 'Maintenance Team', dependencies: ['T37'] },
  { originalId: 'T39', phase: 'handover', title: 'Open other floors as needed by occupancy levels.', priority: 'low', assignee: 'Operations Team', dependencies: ['T37'] },
  { originalId: 'T40', phase: 'handover', title: 'Re-open doors to hotel.', priority: 'low', assignee: 'General Management', dependencies: ['T17 or T18'] },
  { originalId: 'T41', phase: 'handover', title: 'Re-power Public Area equipment, meeting rooms, and Open Stores.', priority: 'low', assignee: 'Internal Team', dependencies: ['T02'] },
  { originalId: 'T42', phase: 'handover', title: 'Turn on all Building signage.', priority: 'low', assignee: 'Internal Team', dependencies: ['T02'] },
  { originalId: 'T43', phase: 'handover', title: 'Re-start all Interactive TV Systems, Background music, and wireless.', priority: 'medium', assignee: 'Internal IT', dependencies: ['T02'] },
  { originalId: 'T44', phase: 'handover', title: 'Power up Laundry and all laundry equipment systems.', priority: 'low', assignee: 'RENZACCI SPA', dependencies: ['T13', 'T28'] },
  { originalId: 'T45', phase: 'handover', title: 'Power up Landscape irrigation systems & Re-instate landscape lighting.', priority: 'low', assignee: 'Maintenance Team', dependencies: ['T02'] },
  { originalId: 'T46', phase: 'handover', title: 'Turn on all elevators.', priority: 'high', assignee: 'Myanmar Jardine Schindler', dependencies: ['T04'] },
  { originalId: 'T47', phase: 'handover', title: 'Re-start Gym and Spa equipment if needed.', priority: 'low', assignee: 'Internal Team', dependencies: ['T02'] },
  { originalId: 'T48', phase: 'renovation', title: 'Super Chlorinate Pool and Backwash pool filters.', priority: 'medium', assignee: 'POOL&SPA Myanmar', dependencies: ['T13'] },
  { originalId: 'T49', phase: 'handover', title: 'Open swimming pool for guest use.', priority: 'high', assignee: 'Leisure Team', dependencies: ['T09', 'T48 (Requires clear results)'] },
  { originalId: 'T50', phase: 'handover', title: 'Activate BMU (Building Maintenance Unit).', priority: 'low', assignee: 'Maintenance Team', dependencies: [] }
];
