import { Project, Task, AssessmentMetric } from './types';

export const initialProjects: Project[] = [
  {
    id: 'p-hotel-1',
    name: 'The Grand Horizon Hotel',
    type: 'hotel',
    description: 'Five-star luxury hotel reopening after comprehensive modernization.',
    manager: 'Eleanor Vance',
    targetDate: '2026-11-01',
  },
  {
    id: 'p-office-1',
    name: 'Apex Tower Renovation',
    type: 'office',
    description: 'Premium Grade-A office tower lobby and facilities upgrade.',
    manager: 'Marcus Thorne',
    targetDate: '2026-08-15',
  }
];

export const initialTasks: Task[] = [
  // Hotel Tasks
  {
    id: 't-h-1',
    projectId: 'p-hotel-1',
    title: 'Structural Integrity Assessment',
    description: 'Complete engineering review of the main lobby and ballroom structures.',
    status: 'completed',
    priority: 'critical',
    phase: 'assessment',
    dueDate: '2026-04-10',
    assignee: 'Engineering Dept',
    isChecklistItem: true,
  },
  {
    id: 't-h-2',
    projectId: 'p-hotel-1',
    title: 'HVAC System Overhaul',
    description: 'Replace legacy air conditioning units with high-efficiency smart systems.',
    status: 'in-progress',
    priority: 'high',
    phase: 'renovation',
    dueDate: '2026-06-15',
    assignee: 'ClimateTech Inc.',
  },
  {
    id: 't-h-3',
    projectId: 'p-hotel-1',
    title: 'Executive Chef Recruitment',
    description: 'Finalize interviews and tasting sessions for the signature restaurant.',
    status: 'in-progress',
    priority: 'high',
    phase: 'staffing',
    dueDate: '2026-05-20',
    assignee: 'HR Department',
  },
  {
    id: 't-h-4',
    projectId: 'p-hotel-1',
    title: 'Procure Frette Linens',
    description: 'Order 1000 sets of premium 800-thread-count linens for all suites.',
    status: 'pending',
    priority: 'medium',
    phase: 'procurement',
    dueDate: '2026-07-01',
    assignee: 'Procurement Team',
  },
  {
    id: 't-h-5',
    projectId: 'p-hotel-1',
    title: 'Final Health & Safety Inspection',
    description: 'City municipal inspection for kitchen and pool areas.',
    status: 'pending',
    priority: 'critical',
    phase: 'handover',
    dueDate: '2026-10-15',
    assignee: 'Compliance Officer',
    isChecklistItem: true,
  },

  // Office Tasks
  {
    id: 't-o-1',
    projectId: 'p-office-1',
    title: 'Elevator Modernization Audit',
    description: 'Assess current elevator speeds and control systems.',
    status: 'completed',
    priority: 'high',
    phase: 'assessment',
    dueDate: '2026-03-20',
    assignee: 'Vertical Systems LLC',
    isChecklistItem: true,
  },
  {
    id: 't-o-2',
    projectId: 'p-office-1',
    title: 'Lobby Marble Restoration',
    description: 'Polish and seal the Italian marble flooring in the main atrium.',
    status: 'in-progress',
    priority: 'medium',
    phase: 'renovation',
    dueDate: '2026-05-10',
    assignee: 'StoneCraft',
  },
  {
    id: 't-o-3',
    projectId: 'p-office-1',
    title: 'Fiber Optic Backbone Upgrade',
    description: 'Install CAT8 and dual-redundant fiber lines for all tenant floors.',
    status: 'review',
    priority: 'critical',
    phase: 'renovation',
    dueDate: '2026-04-30',
    assignee: 'IT Infrastructure',
  },
  {
    id: 't-o-4',
    projectId: 'p-office-1',
    title: 'Smart Access Control Installation',
    description: 'Deploy biometric and mobile-NFC turnstiles in the lobby.',
    status: 'pending',
    priority: 'high',
    phase: 'procurement',
    dueDate: '2026-06-01',
    assignee: 'Security Dept',
  },
  {
    id: 't-o-5',
    projectId: 'p-office-1',
    title: 'Tenant Handover Documentation',
    description: 'Prepare welcome kits and facility manuals for returning tenants.',
    status: 'pending',
    priority: 'low',
    phase: 'handover',
    dueDate: '2026-07-20',
    assignee: 'Property Management',
    isChecklistItem: true,
  }
];

export const seedMetricsData = [
  { category: 'Water & Plumbing', item: 'Storage water tanks', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Calorifiers', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Sump pit lifting stations', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Sanitary system', vendor: 'VP Pine Co.,Ltd' },
  { category: 'Water & Plumbing', item: 'Domestic water pumps', vendor: 'Internal' },
  { category: 'Water & Plumbing', item: 'Hot water / Heat Pump', vendor: 'VP Pine Co.,Ltd' },
  { category: 'Water & Plumbing', item: 'Waste water Treatment system', vendor: 'ATP Solutions & Innovations Co., Ltd.' },
  { category: 'Water & Plumbing', item: 'CHP, CDP PUMP', vendor: 'Aemstronge' },
  { category: 'HVAC & Cooling', item: 'Air intakes (Check if bagged off)', vendor: 'Internal' },
  { category: 'HVAC & Cooling', item: 'Air Chiller Tane 365 Ton', vendor: 'Mr. Narat' },
  { category: 'HVAC & Cooling', item: 'Cooling Tower', vendor: 'TRUWATER THAILAND CO., LTD.' },
  { category: 'HVAC & Cooling', item: 'Air Con System', vendor: 'VP Pine Co.,Ltd' },
  { category: 'HVAC & Cooling', item: 'AHU\'s & FCU\'s (Check filters)', vendor: 'Internal / HVAC Vendor' },
  { category: 'HVAC & Cooling', item: 'Toilet extract & Smoke fans', vendor: 'Internal' },
  { category: 'HVAC & Cooling', item: 'Staircase Pressurisation Fans', vendor: 'Internal' },
  { category: 'HVAC & Cooling', item: 'Plant room ventilation', vendor: 'Internal' },
  { category: 'Electrical & Safety', item: 'MDB System', vendor: 'Mr. Chusak' },
  { category: 'Electrical & Safety', item: 'Generator Machine', vendor: 'Effective Strength EngineeringCo.,Ltd' },
  { category: 'Electrical & Safety', item: 'Car park & plantroom power/lighting', vendor: 'Internal' },
  { category: 'Electrical & Safety', item: 'Fire Alarm System', vendor: 'Mr.Decha' },
  { category: 'Electrical & Safety', item: 'Fire Lift Safety System', vendor: 'Gewarzoe Co., Ltd' },
  { category: 'Electrical & Safety', item: 'CCTV System', vendor: 'Mr.Wasu Yakham' },
  { category: 'Electrical & Safety', item: 'ANSUL System', vendor: 'Magpie Blaztech Co.,Ltd' },
  { category: 'Electrical & Safety', item: 'BMS (Clocks and equipment status)', vendor: 'Internal' },
  { category: 'Kitchen & F&B', item: 'All Kitchen equipment', vendor: 'SUNMEN Corporation' },
  { category: 'Kitchen & F&B', item: 'Gas System', vendor: 'CENTRAL LPG Piping Development Co., Ltd.' },
  { category: 'Kitchen & F&B', item: 'Walk in Chiller Cool Room', vendor: 'B-Cool air Conditioning Co.,Ltd' },
  { category: 'Kitchen & F&B', item: 'Freezers & Upright freezers', vendor: 'Internal / Refrigeration Vendor' },
  { category: 'Kitchen & F&B', item: 'Ice machines', vendor: 'Internal' },
  { category: 'IT & Technology', item: 'IT Network System', vendor: 'Mr.Wasu Yakham' },
  { category: 'IT & Technology', item: 'RCU (Guest Room)', vendor: 'INTRONICS CO.,LTD' },
  { category: 'IT & Technology', item: 'Door VinCard (Guest Room)', vendor: 'FORTRESS LAND Company Limited' },
  { category: 'IT & Technology', item: 'Interactive TV & Background music', vendor: 'Internal / IT' },
  { category: 'IT & Technology', item: 'Wireless connectivity', vendor: 'Internal / IT' },
  { category: 'IT & Technology', item: 'AV System', vendor: 'D.V.I Solution' },
  { category: 'Leisure & General', item: 'Swimming Pool & Filters', vendor: 'POOL&SPA Myanmar CO.,LTD' },
  { category: 'Leisure & General', item: 'Laundry Machine', vendor: 'RENZACCI SPA' },
  { category: 'Leisure & General', item: 'Lift Machine / Elevators', vendor: 'Myanmar Jardine Schindler Ltd' },
  { category: 'Leisure & General', item: 'Gym & Spa equipment', vendor: 'Internal' },
  { category: 'Leisure & General', item: 'Landscape irrigation & lighting', vendor: 'Internal' },
  { category: 'Leisure & General', item: 'Guestrooms & public spaces (Furniture)', vendor: 'Internal / Housekeeping' },
  { category: 'Leisure & General', item: 'Building signage & BMU', vendor: 'Internal' }
];

export const initialMetrics: AssessmentMetric[] = [
  { id: 'm1', projectId: 'p-hotel-1', category: 'Structural', item: 'Foundation Integrity', status: 'pass', notes: 'Inspected by structural engineer. No issues.' },
  { id: 'm2', projectId: 'p-hotel-1', category: 'Systems', item: 'Plumbing Mains', status: 'fail', notes: 'Corrosion detected in East Wing mains. Requires replacement.' },
  { id: 'm3', projectId: 'p-hotel-1', category: 'Safety', item: 'Fire Suppression System', status: 'pending', notes: 'Awaiting municipal pressure test.' },
  { id: 'm4', projectId: 'p-office-1', category: 'Systems', item: 'HVAC Chillers', status: 'pass', notes: 'Operating at 94% efficiency.' },
  { id: 'm5', projectId: 'p-office-1', category: 'Aesthetics', item: 'Facade Glass Integrity', status: 'pass', notes: 'Drone inspection complete.' },
];
