export const officeSeedMetricsData = [
  { category: 'Structural', item: 'Concrete integrity scan (carbonation, chloride ingress)', vendor: 'Structural engineering firm / Concrete NDT specialist' },
  { category: 'Structural', item: 'Façade anchoring & cladding system condition', vendor: 'Façade inspection contractor / Rope access specialists' },
  { category: 'Structural', item: 'Foundation settlement monitoring review', vendor: 'Geotechnical engineering consultant' },
  { category: 'Structural', item: 'Floor loading capacity verification vs. modern IT/server requirements', vendor: 'Structural engineer of record' },
  { category: 'MEP - Mechanical', item: 'HVAC system capacity & efficiency (chillers, AHUs, FCUs)', vendor: 'MEP contractor / Controls specialist' },
  { category: 'MEP - Mechanical', item: 'Indoor air quality testing (CO2, VOCs, particulates)', vendor: 'Environmental testing lab' },
  { category: 'MEP - Mechanical', item: 'Plumbing riser condition & water pressure testing', vendor: 'Licensed plumbing contractor' },
  { category: 'MEP - Electrical', item: 'Main switchgear & transformer condition (oil analysis, thermography)', vendor: 'Electrical contractor / HV specialist' },
  { category: 'MEP - Electrical', item: 'Emergency generator load testing & fuel system inspection', vendor: 'Generator service provider' },
  { category: 'MEP - Electrical', item: 'Power density per floor vs. current standards', vendor: 'Electrical engineer' },
  { category: 'MEP - Electrical', item: 'Lighting system efficacy & daylight harvesting potential', vendor: 'Lighting consultant / Controls vendor' },
  { category: 'Fire Safety', item: 'Sprinkler system coverage & head condition', vendor: 'Fire protection contractor' },
  { category: 'Fire Safety', item: 'Fire alarm system compliance with current codes (addressable panels)', vendor: 'Fire alarm vendor / Code consultant' },
  { category: 'Fire Safety', item: 'Smoke evacuation & pressurization system testing', vendor: 'HVAC/fire contractor' },
  { category: 'Fire Safety', item: 'Egress route capacity & signage compliance', vendor: 'Fire safety consultant / Architect' },
  { category: 'Vertical Transport', item: 'Elevator modernization status (controllers, door operators, drives)', vendor: 'Elevator service provider (Otis/Kone/Thyssen)' },
  { category: 'Vertical Transport', item: 'Escalator condition (if podium retail present)', vendor: 'Escalator maintenance contractor' },
  { category: 'IT/Telecom', item: 'Fiber optic backbone & riser capacity', vendor: 'Telecom infrastructure contractor' },
  { category: 'IT/Telecom', item: 'Server room cooling & redundancy status', vendor: 'Data center consultant' },
  { category: 'IT/Telecom', item: 'BMS (Building Management System) integration capabilities', vendor: 'BMS vendor (Siemens/Honeywell/Johnson)' },
  { category: 'IT/Telecom', item: 'Cellular signal coverage (DAS - Distributed Antenna System)', vendor: 'Telecom carrier / DAS installer' },
  { category: 'Security', item: 'CCTV system resolution & coverage gaps', vendor: 'Security systems integrator' },
  { category: 'Security', item: 'Access control system (card readers, biometrics capability)', vendor: 'Access control vendor' },
  { category: 'Security', item: 'Perimeter intrusion detection', vendor: 'Security consultant' },
  { category: 'Interior', item: 'Common area finishes condition (lobby, corridors, restrooms)', vendor: 'Interior contractor' },
  { category: 'Interior', item: 'Ceiling plenum accessibility for MEP routing', vendor: 'Demolition/Access contractor' },
  { category: 'Interior', item: 'Floor-to-ceiling height vs. modern standards', vendor: 'Architect' },
  { category: 'Exterior', item: 'Curtain wall/window thermal performance (U-value)', vendor: 'Glazing contractor / Energy auditor' },
  { category: 'Exterior', item: 'Waterproofing integrity (roof, podium, basement)', vendor: 'Waterproofing specialist' },
  { category: 'Exterior', item: 'Signage & wayfinding visibility', vendor: 'Signage contractor' },
  { category: 'Sustainability', item: 'Energy audit (baseline consumption analysis)', vendor: 'Energy consultant / LEED AP' },
  { category: 'Sustainability', item: 'Water metering & leak detection systems', vendor: 'Plumbing engineer' },
  { category: 'Sustainability', item: 'Waste management chute & recycling infrastructure', vendor: 'Facilities manager / Waste contractor' },
  { category: 'Compliance', item: 'Building code compliance gap analysis vs. current Myanmar NBC', vendor: 'Code consultant / Local architect' },
  { category: 'Compliance', item: 'ADA/accessibility compliance (ramps, elevators, restrooms)', vendor: 'Accessibility consultant' },
  { category: 'Documentation', item: 'As-built drawings accuracy verification', vendor: 'Document management / BIM consultant' },
  { category: 'Documentation', item: 'Fire safety plan & emergency procedures currency', vendor: 'Fire safety officer' }
];

export const officeSeedTasksData = [
  { originalId: 'O01', phase: 'assessment', title: 'Commission building condition survey & MEP testing', priority: 'high', assignee: 'Project Manager / FM Consultant', dependencies: [] },
  { originalId: 'O02', phase: 'assessment', title: 'Gather as-builts, O&M manuals, previous renovation records', priority: 'medium', assignee: 'Document Controller', dependencies: [] },
  { originalId: 'O03', phase: 'assessment', title: 'Interview current tenants regarding operational pain points', priority: 'medium', assignee: 'Tenant Liaison Manager', dependencies: [] },
  { originalId: 'O04', phase: 'assessment', title: 'Confirm current building code requirements with YCDC', priority: 'high', assignee: 'Regulatory Consultant', dependencies: [] },
  { originalId: 'O05', phase: 'assessment', title: 'Establish energy/water consumption baselines for comparison', priority: 'medium', assignee: 'Sustainability Consultant', dependencies: [] },
  { originalId: 'O06', phase: 'planning', title: 'Develop schematic design & MEP system selection', priority: 'high', assignee: 'Design Architect / MEP Engineer', dependencies: ['O01'] },
  { originalId: 'O07', phase: 'planning', title: 'Create tenant relocation/phasing strategy (if partial occupancy)', priority: 'high', assignee: 'Project Manager / Broker', dependencies: ['O03'] },
  { originalId: 'O08', phase: 'planning', title: 'Prepare detailed cost plan (CAPEX + 10-year OPEX projection)', priority: 'high', assignee: 'Quantity Surveyor', dependencies: ['O06'] },
  { originalId: 'O09', phase: 'planning', title: 'Submit renovation plans to Yangon City Development Committee (YCDC)', priority: 'high', assignee: 'Local Architect / Expeditor', dependencies: ['O06', 'O04'] },
  { originalId: 'O10', phase: 'planning', title: 'Define green building targets (LEED/Green Mark certification)', priority: 'medium', assignee: 'Sustainability Consultant', dependencies: ['O05'] },
  { originalId: 'O11', phase: 'planning', title: 'Develop health & safety plan for occupied building works', priority: 'high', assignee: 'HSE Manager', dependencies: ['O07'] },
  { originalId: 'O12', phase: 'procurement', title: 'Package trade contracts (structural, MEP, fit-out, facade)', priority: 'high', assignee: 'Procurement Manager', dependencies: ['O06', 'O08'] },
  { originalId: 'O13', phase: 'procurement', title: 'Order long-lead items (chillers, generators, elevators)', priority: 'critical', assignee: 'Procurement / MEP Engineer', dependencies: ['O06'] },
  { originalId: 'O14', phase: 'procurement', title: 'Establish material staging area & hoisting strategy', priority: 'medium', assignee: 'Construction Manager', dependencies: ['O11'] },
  { originalId: 'O15', phase: 'procurement', title: 'Coordinate temporary power/water during cutovers', priority: 'high', assignee: 'MEP Contractor / Utility Co.', dependencies: ['O12'] },
  { originalId: 'O16', phase: 'procurement', title: 'Secure construction all-risks & professional indemnity', priority: 'high', assignee: 'Insurance Broker', dependencies: ['O08'] },
  { originalId: 'O17', phase: 'staffing', title: 'Appoint PMC (Project Management Consultant) & Clerk of Works', priority: 'high', assignee: 'Building Owner', dependencies: [] },
  { originalId: 'O18', phase: 'staffing', title: 'Set up site office with resident engineer & safety officer', priority: 'medium', assignee: 'Construction Manager', dependencies: ['O17'] },
  { originalId: 'O19', phase: 'staffing', title: 'Establish tenant communication protocol & helpdesk', priority: 'high', assignee: 'Tenant Liaison', dependencies: ['O07'] },
  { originalId: 'O20', phase: 'staffing', title: 'Engage commissioning agent (CxA) for MEP systems', priority: 'medium', assignee: "Owner's Rep", dependencies: ['O17'] },
  { originalId: 'O21', phase: 'renovation', title: 'Install temporary protection & access scaffolding', priority: 'high', assignee: 'Main Contractor', dependencies: ['O14'] },
  { originalId: 'O22', phase: 'renovation', title: 'Strip out obsolete MEP & finishes (controlled demolition)', priority: 'high', assignee: 'Demolition Subcontractor', dependencies: ['O21'] },
  { originalId: 'O23', phase: 'renovation', title: 'Execute structural strengthening (if required)', priority: 'high', assignee: 'Structural Contractor', dependencies: ['O22'] },
  { originalId: 'O24', phase: 'renovation', title: 'Rough-in new electrical/plumbing/HVAC risers', priority: 'high', assignee: 'MEP Contractor', dependencies: ['O22', 'O23'] },
  { originalId: 'O25', phase: 'renovation', title: 'Upgrade façade glazing & waterproofing systems', priority: 'medium', assignee: 'Façade Contractor', dependencies: ['O21'] },
  { originalId: 'O26', phase: 'renovation', title: 'Complete common area finishes (lobby, corridors, WCs)', priority: 'medium', assignee: 'Fit-Out Contractor', dependencies: ['O24'] },
  { originalId: 'O27', phase: 'renovation', title: 'Modernize elevators (machine roomless conversion if applicable)', priority: 'high', assignee: 'Elevator Vendor', dependencies: ['O13'] },
  { originalId: 'O28', phase: 'renovation', title: 'Test & balance HVAC, integrate BMS, fire alarm commissioning', priority: 'critical', assignee: 'CxA / MEP Contractor', dependencies: ['O24', 'O20'] },
  { originalId: 'O29', phase: 'renovation', title: 'Snagging & defects liability period management', priority: 'medium', assignee: 'Clerk of Works', dependencies: ['O26', 'O28'] },
  { originalId: 'O30', phase: 'handover', title: 'Compile final as-builts, O&M manuals, training records', priority: 'high', assignee: 'Document Controller', dependencies: ['O28', 'O29'], isChecklistItem: true },
  { originalId: 'O31', phase: 'handover', title: 'Conduct FM team training on new systems', priority: 'high', assignee: 'MEP Contractors / Vendors', dependencies: ['O28'], isChecklistItem: true },
  { originalId: 'O32', phase: 'handover', title: 'Obtain fire safety clearance & occupancy permits', priority: 'critical', assignee: 'Regulatory Consultant', dependencies: ['O28', 'O09'], isChecklistItem: true },
  { originalId: 'O33', phase: 'handover', title: 'Final account settlement & retention release', priority: 'medium', assignee: 'Quantity Surveyor', dependencies: ['O29'], isChecklistItem: true },
  { originalId: 'O34', phase: 'handover', title: 'Transition to facilities management & establish SLA', priority: 'high', assignee: 'Project Manager / FM Consultant', dependencies: ['O30', 'O31'], isChecklistItem: true }
];
